---
name: Web Frameworks Energy Test
author: Arne Tarara <arne@green-coding.berlin>
description: Energy test on top of the splendid performance tests for web frameworks from https://github.com/the-benchmarker/web-frameworks

sci:
  R_d: request

services:
  runner:
    image: ruby:3.3.0-bookworm
    setup-commands:
      - commands: apt update
      - commands: apt install wrk -y
      - commands: bundle config set path /tmp/repo/vendor/bundle
#      This is now done in the Github aciton beforehand
#      - bundle install --gemfile=/tmp/repo-writable/Gemfile

  framework:
    build:
      dockerfile: .Dockerfile.default
      context: java/spring

flow:

  - name: Benchmark
    container: runner
    commands:
      - type: console
        shell: bash
        command: cd /tmp/repo && HOSTNAME=framework ENGINE=default LANGUAGE=java FRAMEWORK=spring DATABASE_URL=None bundle exec rake collect
        log-stdout: true
        read-notes-stdout: true
        read-sci-stdout: true
